---
title: "Results of 4th Down Predictive and Causal 4th Down Analysis"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo=FALSE)
```


This section is for notes. The interpretation will be as I go but I want this to be a general outline.

PLAYERS ARE PUT INTO THEIR SLOTS BASED ON DEPTH CHART DATA


* **QB (Slots 1-3):** Quarterbacks. Most plays will only have one QB on the field (slot 1)
* **BACKS (Slots 4-7):** Running backs (RB) and fullbacks (FB).
* **WR (Slots 8-13):** Wide receivers. Teams typically use 2-4 WRs on a given play.
* **TE (Slots 14-16):** Tight ends. These players can act as both receivers and blockers.
* **OL (Slots 17-24):** Offensive line. This includes the center (C), guards (G), and tackles (T). There are usually 5 OL on the field.


* **DL (Slots 1-8):** Defensive line. This includes defensive ends (DE), defensive tackles (DT), and nose tackles (NT). 
* **LB (Slots 9-14):** Linebackers. This can include middle linebackers (MLB), inside linebackers (ILB), and outside linebackers (OLB).
* **CB (Slots 15-19):** Cornerbacks.
* **S (Slots 20-23):** Safeties. This includes free safeties (FS) and strong safeties (SS).
